[workspace]
resolver = "2"
members = [
    "purpura/lexer",
    "purpura/parser",
    "purpura/location",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
