[package]
name = "checker"
version = "0.1.0"
edition = "2021"

[dependencies]
location = { path = "../location" }
desugar = { path = "../desugar" }
report = { path = "../report" }
im-rc = { workspace = true }
