
#[derive(Debug, PartialEq, Eq)]
pub enum Token {
    Identifier(String),
    Number(String),
    Fn,
    Let,
    Match,
    Spec,
    Data,
    Equal,
    EqualEqual,
    FatArrow,
    Bang,
    NotEqual,
    LessThan,
    GreaterThan,
    LessEqual,
    GreaterEqual,
    BiOp(char),
    Comma,
    Dot,
    Semicolon,
    Pipe,
    Arrow,
    LeftParenthesis,
    RightParenthesis,
    LeftBrace,
    RightBrace,
    String(String),
    Unexpected(String),
    Comment(String),
    EOF
}
